spring:
  datasource:
    username: root
    password: 9527
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fivechase?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&serverTimezone=GMT%2B8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085
